version: "3"
services:
  saysomething:
    container_name: SaySomething
    build:
      context: .
      dockerfile: Dockerfile
    image: davidbootle/saysomething
    ports:
      - "4173:4173"
    command: ["npm", "run", "preview"]
  saysomethingbackend:
    container_name: SaySomethingBackend
    build:
      context: ./api
      dockerfile: Dockerfile
    image: davidbootle/saysomethingbackend
    ports:
      - "5200:5200"
    command: ["npm", "run", "dev"]