version: "3"
services:
  saysomething:
    container_name: SaySomething
    build:
      context: .
      dockerfile: Dockerfile
    image: davidbootle/saysomething
    ports:
      - "4173:4173"
    command: ["static-server", "-p", "4173"]